#!/usr/bin/env zsh
# sourced: https://github.com/falconindy/pkgfile/blob/master/extra/command-not-found.zsh

local pkgs cmd="$1"

pkgs=(${(f)"$(pkgfile -b -v -- "$cmd" 2>/dev/null)"})
if [[ -n "$pkgs" ]]; then
  printf '%s may be found in the following packages:\n' "$cmd"
  printf '  %s\n' $pkgs[@]
else
  printf 'zsh: command not found: %s\n' "$cmd"
fi 1>&2

return 127
