#! /bin/sh

bspc monitor DP-4 -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

feh --bg-scale $HOME/Pictures/Wallpapers/3440x1440/ &
picom &
sxhkd &
dunst &
$XDG_CONFIG_HOME/polybar/launch.sh
